# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c242a2974297ba41c20df77520c814cc"
application_url = "https://videocrat.com/auth/install"
embedded = true
name = "Videocrat"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,write_files,read_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
 "https://videocrat.com/auth/callback"
]
